name: build

on: 
  workflow_dispatch:
    inputs:
      access:
        description: "Default access level"
        required: false
        default: "*"
        type: string

jobs:
  release:
    runs-on: self-hosted

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Build
        env:
          ACCESS: ${{ inputs.access }}
        run: |
          npm install
          npm run access -- $env:ACCESS
          npm run update:cst
          npm run format
          npm run make

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: glimmr-setup.exe
          path: dist/squirrel-windows/glimmr-setup.exe
